<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('monthly_payrolls', function (Blueprint $table) {
            if (! Schema::hasColumn('monthly_payrolls', 'half_days')) {
                // Computed correctly by the controller but never persisted —
                // this column was missing entirely (confirmed via
                // Schema::hasColumn during Phase 0 verification), not just
                // absent from $fillable.
                $table->decimal('half_days', 5, 2)->default(0)->after('present_days');
            }

            if (! Schema::hasColumn('monthly_payrolls', 'engine_version')) {
                // Distinguishes payslips generated by the legacy fixed-column
                // engine from the new dynamic component engine, so old rows
                // keep rendering unchanged and new runs are traceable.
                $table->string('engine_version', 20)->default('legacy_fixed')->after('employee_payroll_id');
            }
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('monthly_payrolls', function (Blueprint $table) {
            if (Schema::hasColumn('monthly_payrolls', 'half_days')) {
                $table->dropColumn('half_days');
            }
            if (Schema::hasColumn('monthly_payrolls', 'engine_version')) {
                $table->dropColumn('engine_version');
            }
        });
    }
};
