<?php

namespace App\Services\Payroll;

use App\Models\MonthlyPayroll;
use App\Models\OvertimeRequest;
use App\Models\PayrollComponent;
use App\Models\PayrollEmployeeStructure;
use App\Services\Attendance\OvertimeApprovalService;
use App\Services\Payroll\Legacy\LegacyPayrollCalculator;
use App\Services\RbacService;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Edit Payroll — saving a pending payslip after HR changed it, for both
 * engines, plus the dynamic engine's live preview. Moved out of
 * MonthlyPayrollController unchanged (code-quality plan, Phase 1); the
 * controller keeps validation and turns a PayrollEditException into the same
 * redirect + message the screen always showed.
 *
 *  - Legacy payslips: the submitted amounts are saved as typed (plus any
 *    pending overtime the editor chose to approve), components rebuilt and the
 *    loan ledger resynced — saveLegacy().
 *  - Dynamic payslips: recomputed through PayrollCalculationEngine with the
 *    edited day counts, then manual component overrides win — saveDynamic().
 */
class PayrollEditService
{
    public function __construct(
        private LegacyPayrollCalculator $calculator,
        private PayslipWriter $payslips,
        private PayrollLoanApplier $loans,
        private LoanDeductionService $loanDeductionService,
        private OvertimeApprovalService $overtimeApprovalService,
    ) {}

    /**
     * Dynamic Edit/Update is used only for a payslip generated by the dynamic
     * engine (its own engine_version, not the company's current flag) whose
     * employee still has an effective PayrollEmployeeStructure for that month;
     * every other payslip keeps the legacy form.
     */
    public function usesDynamicEdit(?MonthlyPayroll $monthlyPayroll): bool
    {
        if (! $monthlyPayroll || $monthlyPayroll->engine_version !== 'dynamic_v1') {
            return false;
        }

        return PayrollEmployeeStructure::withoutGlobalScope('tenant')
            ->where('tenant_id', $monthlyPayroll->tenant_id)
            ->forUser($monthlyPayroll->user_id)
            ->effective(Carbon::createFromFormat('Y-m', $monthlyPayroll->payroll_month)->endOfMonth()->toDateString())
            ->exists();
    }

    /**
     * Everything the Edit Payroll screen shows: loan / advance instalments due
     * (incl. what this payslip already collected), approved and pending overtime
     * with its price, and — for a dynamic-engine payslip — its components.
     */
    public function editFormData(MonthlyPayroll $monthlyPayroll): array
    {
        $months = [];
        for ($i = 0; $i < 12; $i++) {
            $date = now()->subMonths($i);
            $months[$date->format('Y-m')] = $date->format('F Y');
        }
        $userPayroll = $monthlyPayroll->user->payrolls()
            ->where('is_current', 1)
            ->where('status', 1)
            ->first();

        // What this payslip has to collect, INCLUDING what it already collected (its own share is
        // undone inside a transaction that is always rolled back — read-only).
        DB::beginTransaction();
        try {
            $this->loanDeductionService->revokeForPayroll($monthlyPayroll->id, $monthlyPayroll->tenant_id);
            $loanDueItems = $this->loanDeductionService->dueItems(
                $monthlyPayroll->user_id,
                $monthlyPayroll->tenant_id,
                $monthlyPayroll->payroll_month,
                \App\Models\Loan::KIND_LOAN
            );
            // Salary advances against this month — their own block on the edit screen.
            $advanceDueItems = $this->loanDeductionService->dueItems(
                $monthlyPayroll->user_id,
                $monthlyPayroll->tenant_id,
                $monthlyPayroll->payroll_month,
                \App\Models\Loan::KIND_SALARY_ADVANCE
            );
        } finally {
            DB::rollBack();
        }
        $loanDueTotal = round($loanDueItems->sum('balance_due'), 2);
        $advanceDueTotal = round($advanceDueItems->sum('balance_due'), 2);

        // ---- Overtime: approved breakdown + non-approved (pending) preview ----
        [$otYear, $otMonth] = explode('-', $monthlyPayroll->payroll_month);

        $approvedOvertimeRequests = OvertimeRequest::forMonth($otYear, $otMonth)
            ->approved()
            ->where('user_id', $monthlyPayroll->user_id)
            ->orderBy('date')
            ->get();

        $pendingOvertimeRequests = OvertimeRequest::forMonth($otYear, $otMonth)
            ->pending()
            ->where('user_id', $monthlyPayroll->user_id)
            ->orderBy('date')
            ->get();

        $canApproveOvertime = app(RbacService::class)->can(auth()->user(), 'overtime', 'approve');

        $overtimeRateInfo = app(\App\Services\Payroll\OvertimePayService::class)->describe((int) $monthlyPayroll->tenant_id, (int) $monthlyPayroll->user_id);
        $overtimeRateMultiplier = $overtimeRateInfo['multiplier'];
        $overtimeFixedRate = $overtimeRateInfo['fixed'];

        $pendingOvertimeHours = round(
            (float) $pendingOvertimeRequests->sum(fn ($r) => (float) $r->final_overtime_hours), 2
        );
        $pendingOvertimeCalc = $this->calculator->overtimeAmountForHours(
            $pendingOvertimeHours, $userPayroll, $monthlyPayroll->payroll_month,
            $monthlyPayroll->total_working_days, $monthlyPayroll->tenant_id
        );
        $pendingOvertimeRate = $pendingOvertimeCalc['rate'];
        $pendingOvertimeAmount = $pendingOvertimeCalc['amount'];

        // Dynamic-engine branch — additive, legacy tenants get $isDynamic
        // = false and the view falls through to its existing hardcoded
        // Earnings/Deductions/Employer fields completely unchanged. Gated
        // on THIS payroll row's own engine_version, not just the
        // tenant's current flag — a tenant can switch to the dynamic
        // engine after some of its payrolls were already created via
        // the legacy path, and editing those old rows must keep using
        // the legacy form (their data has no dynamic-engine lineage to
        // recompute against), not whatever the employee's structure
        // looks like today.
        $isDynamic = $monthlyPayroll->engine_version === 'dynamic_v1';
        $dynamicComponents = null;
        if ($isDynamic) {
            try {
                $dynamicComponents = app(\App\Services\Payroll\PayrollCalculationEngine::class)
                    ->resolveEmployeeComponents($monthlyPayroll->user, $monthlyPayroll->tenant_id, $monthlyPayroll->payroll_month);
            } catch (\Throwable $e) {
                // No PayrollEmployeeStructure effective for this employee/month
                // (e.g. this payroll predates the dynamic engine for them) —
                // fall back to the legacy field set rather than a 500.
                Log::warning('Dynamic component resolve failed in edit(): '.$e->getMessage());
                $isDynamic = false;
            }
        }

        return compact(
            'monthlyPayroll', 'months', 'userPayroll', 'loanDueItems', 'loanDueTotal', 'advanceDueItems', 'advanceDueTotal',
            'approvedOvertimeRequests', 'pendingOvertimeRequests', 'canApproveOvertime',
            'overtimeRateMultiplier', 'overtimeFixedRate', 'overtimeRateInfo', 'pendingOvertimeRate', 'pendingOvertimeHours', 'pendingOvertimeAmount',
            'isDynamic', 'dynamicComponents'
        );
    }

    /**
     * Net pay the legacy form would save (incl. pending overtime the editor
     * chose to approve) — validation refuses a negative one unless confirmed.
     */
    public function legacyNetPreview(Request $request, $id): float
    {
        // Preview (read-only) of the pending-overtime amount that would be
        // auto-approved and folded into this payslip, so the negative-net-pay
        // gate below sees the real total -- the actual approval + authoritative
        // recompute happen again, for real, inside the transaction further down.
        $pendingOvertimePreviewAmount = 0.0;
        if ($request->boolean('include_pending_overtime')) {
            $mpForPreview = MonthlyPayroll::find($id);
            if ($mpForPreview) {
                $requestedIdsForPreview = array_map('intval', (array) $request->input('pending_overtime_request_ids', []));
                [$pyYear, $pyMonth] = explode('-', $mpForPreview->payroll_month);
                $eligiblePreview = OvertimeRequest::forMonth($pyYear, $pyMonth)
                    ->pending()
                    ->where('user_id', $mpForPreview->user_id)
                    ->where('tenant_id', $mpForPreview->tenant_id)
                    ->whereIn('id', $requestedIdsForPreview)
                    ->get();
                $previewUserPayroll = $mpForPreview->user->payrolls()
                    ->where('is_current', 1)->where('status', 1)->first();
                $previewHours = round((float) $eligiblePreview->sum(fn ($r) => (float) $r->final_overtime_hours), 2);
                $pendingOvertimePreviewAmount = $this->calculator->overtimeAmountForHours(
                    $previewHours, $previewUserPayroll, $mpForPreview->payroll_month,
                    $mpForPreview->total_working_days, $mpForPreview->tenant_id
                )['amount'];
            }
        }

        // Computed here (not just inside the try block) so the
        // negative-net-pay confirmation gate below can run as part of
        // validation, before anything is persisted.
        $grossEarningsPreview = (float) $request->basic_salary
            + (float) $request->hra
            + (float) $request->conveyence
            + (float) $request->medical_allowance
            + (float) ($request->children_allowance ?? 0)
            + (float) ($request->post_allowance ?? 0)
            + (float) ($request->leave_travel_allowance ?? 0)
            + (float) ($request->monthly_incentive ?? 0)
            + (float) ($request->special_allowance ?? 0)
            + (float) ($request->overtime_amount ?? 0)
            + (float) ($request->shift_allowance_amount ?? 0)
            + $pendingOvertimePreviewAmount;

        $loanDeductionEnabled = $request->boolean('loan_deduction_enabled', true);
        $requestedLoanDeduction = $loanDeductionEnabled ? (float) ($request->loan_deduction ?? 0) : 0.0;
        // Salary advance against this month — edited and applied separately from loan EMIs.
        $advanceEnabled = $request->boolean('salary_advance_deduction_enabled', true);
        $requestedAdvance = $advanceEnabled ? (float) ($request->salary_advance_deduction ?? 0) : 0.0;

        $totalDeductionsPreview = (float) $request->provident_fund
            + (float) $request->esi
            + (float) $request->professional_tax
            + (float) ($request->tds ?? 0)
            + $requestedLoanDeduction
            + $requestedAdvance
            + (float) ($request->other_deductions ?? 0);

        $netPayablePreview = round($grossEarningsPreview - $totalDeductionsPreview, 2);

        return $netPayablePreview;
    }

    /** Save the legacy Edit Payroll form. Throws PayrollEditException with the message the screen shows. */
    public function saveLegacy(Request $request, $id): void
    {
        $loanDeductionEnabled = $request->boolean('loan_deduction_enabled', true);
        $requestedLoanDeduction = $loanDeductionEnabled ? (float) ($request->loan_deduction ?? 0) : 0.0;
        // Salary advance against this month — edited and applied separately from loan EMIs.
        $advanceEnabled = $request->boolean('salary_advance_deduction_enabled', true);
        $requestedAdvance = $advanceEnabled ? (float) ($request->salary_advance_deduction ?? 0) : 0.0;

        try {
            DB::beginTransaction();

            // lockForUpdate() -- two concurrent saves of the same payslip
            // (e.g. two admins with the edit page open at once) could
            // otherwise interleave their component delete-then-recreate and
            // loan-ledger resync, corrupting either.
            $monthlyPayroll = MonthlyPayroll::lockForUpdate()->findOrFail($id);

            if (auth()->user()->cannot('update', $monthlyPayroll)) {
                throw new PayrollEditException('Only pending payroll records can be edited.');
            }

            if ($monthlyPayroll->tenant_id && app(\App\Services\Attendance\PeriodLockService::class)->isLocked($monthlyPayroll->tenant_id, $monthlyPayroll->payroll_month)) {
                throw new PayrollEditException($monthlyPayroll->payroll_month.' is locked. Reopen the period before editing this payroll.');
            }

            // Check if hour-based
            $userPayroll = $monthlyPayroll->user->payrolls()
                ->where('is_current', 1)
                ->where('status', 1)
                ->first();

            $isHourBased = $userPayroll && $userPayroll->payrollMaster
                && $userPayroll->payrollMaster->payroll_calculation_type === 'hour_based';

            // ---- Overtime: the "approved" hours/amount inputs stay exactly
            // what the payroll editor typed (fully editable, unchanged
            // behavior). If they opted to include non-approved overtime,
            // re-verify permission + the request IDs server-side (never trust
            // the checkbox/IDs from the client alone), auto-approve exactly
            // those requests via the same bulk-approve path the Overtime page
            // uses, and fold the *server-computed* delta on top. ----
            $overtimeHours = (float) ($request->overtime_hours ?? 0);
            $overtimeAmount = (float) ($request->overtime_amount ?? 0);

            if ($request->boolean('include_pending_overtime')) {
                $requestedOvertimeIds = array_map('intval', (array) $request->input('pending_overtime_request_ids', []));
                [$otYear, $otMonth] = explode('-', $monthlyPayroll->payroll_month);
                $eligibleOvertimeIds = OvertimeRequest::forMonth($otYear, $otMonth)
                    ->pending()
                    ->where('user_id', $monthlyPayroll->user_id)
                    ->where('tenant_id', $monthlyPayroll->tenant_id)
                    ->whereIn('id', $requestedOvertimeIds)
                    ->pluck('id')
                    ->all();

                if (! empty($eligibleOvertimeIds)) {
                    $approvalResult = $this->overtimeApprovalService->bulkApprove(
                        auth()->user(), $monthlyPayroll->tenant_id, $eligibleOvertimeIds
                    );

                    if (! $approvalResult['authorized']) {
                        throw new PayrollEditException('You do not have permission to approve overtime requests.', withInput: true);
                    }

                    if ($approvalResult['approved_count'] > 0) {
                        $newlyApproved = OvertimeRequest::whereIn('id', $approvalResult['approved_ids'])->get();
                        $newlyApprovedHours = round(
                            (float) $newlyApproved->sum(fn ($r) => (float) $r->final_overtime_hours), 2
                        );
                        $newlyApprovedCalc = $this->calculator->overtimeAmountForHours(
                            $newlyApprovedHours, $userPayroll, $monthlyPayroll->payroll_month,
                            $monthlyPayroll->total_working_days, $monthlyPayroll->tenant_id
                        );

                        $overtimeHours += $newlyApprovedHours;
                        $overtimeAmount += $newlyApprovedCalc['amount'];
                    }
                }
            }

            $grossEarnings = $request->basic_salary
                + $request->hra
                + $request->conveyence
                + $request->medical_allowance
                + ($request->children_allowance ?? 0)
                + ($request->post_allowance ?? 0)
                + ($request->leave_travel_allowance ?? 0)
                + ($request->monthly_incentive ?? 0)
                + ($request->special_allowance ?? 0)
                + $overtimeAmount
                + (float) ($request->shift_allowance_amount ?? 0);

            $totalDeductions = $request->provident_fund
                + $request->esi
                + $request->professional_tax
                + ($request->tds ?? 0)
                + $requestedLoanDeduction
                + $requestedAdvance
                + ($request->other_deductions ?? 0);

            $netPayable = $grossEarnings - $totalDeductions;

            $loanDueTotal = $this->loanDeductionService->totalDue(
                $monthlyPayroll->user_id,
                $monthlyPayroll->tenant_id,
                $monthlyPayroll->payroll_month,
                \App\Models\Loan::KIND_LOAN
            );
            $advanceDueTotal = $this->loanDeductionService->totalDue(
                $monthlyPayroll->user_id,
                $monthlyPayroll->tenant_id,
                $monthlyPayroll->payroll_month,
                \App\Models\Loan::KIND_SALARY_ADVANCE
            );

            $updateData = [
                'payroll_month' => $request->payroll_month,
                'present_days' => $request->present_days,
                'paid_leaves' => $request->paid_leaves ?? 0,
                'overtime_hours' => $overtimeHours,
                'basic_salary' => $request->basic_salary,
                'hra' => $request->hra,
                'conveyence' => $request->conveyence,
                'medical_allowance' => $request->medical_allowance,
                'children_allowance' => $request->children_allowance ?? 0,
                'post_allowance' => $request->post_allowance ?? 0,
                'leave_travel_allowance' => $request->leave_travel_allowance ?? 0,
                'monthly_incentive' => $request->monthly_incentive ?? 0,
                'special_allowance' => $request->special_allowance ?? 0,
                'overtime_amount' => $overtimeAmount,
                'shift_allowance_amount' => (float) ($request->shift_allowance_amount ?? 0),
                'provident_fund' => $request->provident_fund,
                'esi' => $request->esi,
                'professional_tax' => $request->professional_tax,
                'tds' => $request->tds ?? 0,
                'loan_deduction' => $requestedLoanDeduction,
                'loan_deduction_enabled' => $loanDeductionEnabled,
                'loan_deduction_computed' => $loanDueTotal,
                'salary_advance_deduction' => $requestedAdvance,
                'salary_advance_deduction_computed' => $advanceDueTotal,
                'other_deductions' => $request->other_deductions ?? 0,
                'gross_earnings' => $grossEarnings,
                'total_deductions' => $totalDeductions,
                'net_payable' => $netPayable,
                'remarks' => $request->remarks
                    ? $monthlyPayroll->remarks.' | Updated: '.$request->remarks
                    : $monthlyPayroll->remarks,
            ];

            // If hour-based, also update actual_worked_hours
            if ($isHourBased && $request->has('actual_worked_hours')) {
                $updateData['actual_worked_hours'] = $request->actual_worked_hours;
            }

            // Keep the "Shift Allowance (Night × 12 days)" label the generated payslip had.
            $shiftAllowanceName = PayrollComponent::where('monthly_payroll_id', $id)
                ->where('component_name', 'like', 'Shift Allowance%')->value('component_name') ?? 'Shift Allowance';

            $monthlyPayroll->update($updateData);

            PayrollComponent::where('monthly_payroll_id', $id)->delete();

            $earnings = [
                'basic' => $request->basic_salary,
                'hra' => $request->hra,
                'conveyence' => $request->conveyence,
                'medical' => $request->medical_allowance,
                'children' => $request->children_allowance ?? 0,
                'post' => $request->post_allowance ?? 0,
                'lta' => $request->leave_travel_allowance ?? 0,
                'incentive' => $request->monthly_incentive ?? 0,
                'special' => $request->special_allowance ?? 0,
                'overtime' => $overtimeAmount,
                'shift_allowance' => (float) ($request->shift_allowance_amount ?? 0),
            ];

            $employeeDeductions = [
                'pf' => $request->provident_fund,
                'esi' => $request->esi,
                'pt' => $request->professional_tax,
                'tds' => $request->tds ?? 0,
                'loan' => $requestedLoanDeduction,
                'advance' => $requestedAdvance,
                'other' => $request->other_deductions ?? 0,
            ];

            $employerContributions = [
                'employer_pf' => $monthlyPayroll->employer_provident_fund ?? 0,
                'employer_esi' => $monthlyPayroll->employer_esi ?? 0,
            ];

            $this->payslips->savePayrollComponents($id, $earnings, $employeeDeductions, $employerContributions,
                ['shift_allowance' => $shiftAllowanceName]);

            // Sync the loan ledger to match what was actually saved on this
            // payslip -- idempotent (applyDeduction()/revokeForPayroll()
            // both first reverse whatever this monthly_payroll_id previously
            // applied), so re-editing and resaving never double-deducts.
            // Advance and loan EMIs are synced separately (each undoes only its own earlier share).
            $this->loans->updateLoanRepayments($monthlyPayroll->user_id, $monthlyPayroll->payroll_month, $requestedAdvance,
                $monthlyPayroll->tenant_id, $monthlyPayroll->id, \App\Models\Loan::KIND_SALARY_ADVANCE);
            $this->loans->updateLoanRepayments($monthlyPayroll->user_id, $monthlyPayroll->payroll_month, $requestedLoanDeduction,
                $monthlyPayroll->tenant_id, $monthlyPayroll->id, \App\Models\Loan::KIND_LOAN);

            DB::commit();
        } catch (PayrollEditException $e) {
            DB::rollBack();

            throw $e;
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Payroll update error: '.$e->getMessage());

            throw new PayrollEditException('Failed to update payroll: '.$e->getMessage(), withInput: true, previous: $e);
        }
    }

    /**
     * Save the dynamic Edit Payroll form: always recomputed through
     * PayrollCalculationEngine::calculate() (the engine store() uses) with the
     * submitted day-count overrides, so Week Off/Absent/Holiday edits flow
     * through real per-component proration; individual components can still
     * be overridden afterwards (manual edit wins).
     */
    public function saveDynamic(Request $request, MonthlyPayroll $monthlyPayroll, array $data, bool $includeLoanDeductions): void
    {
        try {
            DB::beginTransaction();

            // Undo what this payslip already collected first: the engine only counts instalments
            // still unpaid, so without this a re-save found nothing due and dropped the deduction.
            $this->loanDeductionService->revokeForPayroll($monthlyPayroll->id, $monthlyPayroll->tenant_id);

            $result = app(PayrollCalculationEngine::class)->calculate(
                $monthlyPayroll->user,
                $monthlyPayroll->tenant_id,
                $monthlyPayroll->payroll_month,
                $includeLoanDeductions,
                $this->dayOverridesFromRequest($data, $monthlyPayroll)
            );
            $this->loans->capDynamicLoanAndAdvance($result, (int) $monthlyPayroll->user_id, $monthlyPayroll->payroll_month);

            $this->applyComponentOverrides($result, $data['components'] ?? []);

            if (! $request->boolean('confirm_negative_net_payable') && $result['net_payable'] < 0) {
                throw new PayrollEditException(
                    'Net payable would be negative (₹'.number_format($result['net_payable'], 2).'). Check "proceed anyway" to confirm.',
                    withInput: true
                );
            }

            $this->payslips->applyDynamic($monthlyPayroll, $result, $includeLoanDeductions);

            if ($request->filled('remarks')) {
                $monthlyPayroll->remarks = $request->remarks;
                $monthlyPayroll->save();
            }

            DB::commit();
        } catch (PayrollEditException $e) {
            DB::rollBack();

            throw $e;
        } catch (\Throwable $e) {
            DB::rollBack();
            Log::error('Dynamic payroll update error: '.$e->getMessage());

            throw new PayrollEditException('Failed to update payroll: '.$e->getMessage(), withInput: true, previous: $e);
        }
    }

    /**
     * Read-only live preview for the dynamic Edit form — the exact same
     * PayrollCalculationEngine::calculate() call saveDynamic() makes, so what
     * HR sees while editing can never drift from what gets saved.
     */
    public function preview(MonthlyPayroll $monthlyPayroll, array $data, bool $includeLoanDeductions): array
    {
        // Read-only: undo this payslip's own loan / advance share inside a transaction that is
        // always rolled back, so the preview counts them as due (same as the real save).
        DB::beginTransaction();
        try {
            $this->loanDeductionService->revokeForPayroll($monthlyPayroll->id, $monthlyPayroll->tenant_id);
            $result = app(PayrollCalculationEngine::class)->calculate(
                $monthlyPayroll->user,
                $monthlyPayroll->tenant_id,
                $monthlyPayroll->payroll_month,
                $includeLoanDeductions,
                $this->dayOverridesFromRequest($data, $monthlyPayroll)
            );
            $this->loans->capDynamicLoanAndAdvance($result, (int) $monthlyPayroll->user_id, $monthlyPayroll->payroll_month);
        } finally {
            DB::rollBack();
        }

        $grouped = collect($result['line_items'])->groupBy('component_type');

        return [
            'earnings' => $grouped->get('earning', collect())->values(),
            'deductions' => $grouped->get('deduction', collect())->values(),
            'employer_contributions' => $grouped->get('employer_contribution', collect())->values(),
            'reimbursements' => $grouped->get('reimbursement', collect())->values(),
            'gross_earnings' => $result['gross_earnings'],
            'total_deductions' => $result['total_deductions'],
            'net_payable' => $result['net_payable'],
            'payable_days' => $result['context']['payable_days'],
            'absent_days' => $result['context']['absent_days'],
        ];
    }

    /**
     * present_days/paid_leave_days/week_offs/holidays for
     * PayrollAttendanceContextBuilder::build()'s $dayOverrides — unset
     * fields fall back to this payroll's current stored value rather than
     * 0, so submitting the form without touching every single day-count
     * field can't accidentally zero one out.
     */
    private function dayOverridesFromRequest(array $data, MonthlyPayroll $monthlyPayroll): array
    {
        return [
            'present_days' => (float) $data['present_days'],
            'paid_leave_days' => (float) ($data['paid_leaves'] ?? $monthlyPayroll->paid_leaves ?? 0),
            'week_offs' => (float) ($data['week_offs'] ?? $monthlyPayroll->week_offs ?? 0),
            'holidays' => (float) ($data['holidays'] ?? $monthlyPayroll->holidays ?? 0),
        ];
    }

    /**
     * Manual per-component amount overrides (submitted from the dynamic
     * Edit form's editable component fields, keyed by component code) take
     * precedence over the freshly recomputed amount for that one component
     * — same "manual edit wins" precedent the legacy form already
     * establishes for its own fields — then re-sums the affected totals.
     */
    private function applyComponentOverrides(array &$result, array $overrides): void
    {
        if (empty($overrides)) {
            return;
        }

        foreach ($result['line_items'] as &$li) {
            // A reimbursement line is fixed by the approved claim - payroll pays exactly that amount.
            if ($li['code'] !== \App\Services\Expense\ExpenseReimbursementPayrollService::CODE && array_key_exists($li['code'], $overrides)) {
                $li['amount'] = round((float) $overrides[$li['code']], 2);
            }
        }
        unset($li);

        $result['gross_earnings'] = round(collect($result['line_items'])->where('component_type', 'earning')->sum('amount'), 2);
        $result['total_deductions'] = round(collect($result['line_items'])->where('component_type', 'deduction')->sum('amount'), 2);
        $result['net_payable'] = round($result['gross_earnings'] - $result['total_deductions'], 2);

        // A manually edited loan / advance line is what the ledger must collect.
        $lines = collect($result['line_items'])->keyBy('code');
        if ($lines->has('loan_deduction')) {
            $result['loan_deduction'] = round((float) $lines['loan_deduction']['amount'], 2);
        }
        if ($lines->has('salary_advance_deduction')) {
            $result['salary_advance_deduction'] = round((float) $lines['salary_advance_deduction']['amount'], 2);
        }
    }
}
